version: '2.1'

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx-container
    ports:
      - "3000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - php-fpm

  php-fpm:
    build: ./docker/php7
    container_name: hostgator-api-container
    links:
      - mysql:mysql
    environment:
      - COMPAT=${PHP_SERVER:-7.3}
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
      - DB_HOSTNAME=mysql
      - DB_DATABASE=hostgator_db
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_HOST=hostgator_mysql
    volumes:
     - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build: ./docker/mysql
    container_name: hostgator_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hostgator_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10